version: "3"

services:
  tinyproxy:
    build:
      context: .
      containerfile: Containerfile
    image: cloudflare-tinyproxy:latest
    container_name: cloudflare-tinyproxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro,Z
